name: Deploy React to GH Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
